<?php

namespace App\Keys;

use App\Helpers\RandomHelper;
use App\Helpers\ResultHelper;

class De3Cang extends Base
{
    protected string $key = 'de3cang';
    protected int $range_day = 1;
    protected bool $checkOnlySpecial = false;
    private array $numberTmp;

    protected function setNewNumber(): void
    {
        $this->number = RandomHelper::getRandomNumber(3, 6);
    }
    protected function logicChangeResult(array $loto = []): bool
    {
        $this->numberTmp = $this->number;
        $this->number = array_map(fn($i) => substr($i, -2), $this->number);
        if (parent::logicChangeResult($loto)){
            $this->number = $this->numberTmp;
            $loto3Cang = ResultHelper::getLoto($loto, 3);
            $intersect = array_intersect($this->number, $loto3Cang);
            $intersect = array_count_values($intersect);
            $this->number_win = $this->number_win + $intersect;
            return true;
        }
        return false; // TODO: Change the autogenerated stub
    }
}
